myurl: https://david.summerhays.net
title: "Summerhays Blog"
keywords: politics, conservatism, summerhays, blog
short_title: Summerhays blog
description: The hazards of being me
# url: [Canonical URL for this blog]
author:
  name: David Summerhays
#  url: [URL of your website]

paginate: 3
year: 2021
emoji_dir: ./images/emoji
show_downloads: false
include: ['_pages']
defaults:
  - scope: 
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "David"
plugins: [jekyll-paginate]
