title: David's politics blog
description: The hazards of studying conservatism
# url: [Canonical URL for this blog]
author:
  name: David Summerhays
  email: david@summerhays.net
#  url: [URL of your website]

paginate: 3
year: 2020
show_downloads: false
include: '_pages'
defaults:
  - scope: 
      path: "_pages" # an empty string here means all files in the project
      type: "pages"
    values:
      layout: "default"
      permalink: "/:basename/"
  - scope:
      path: "_posts" # an empty string here means all files in the project
      type: "posts"
    values:
      layout: "post"
      author: "David"
